In [33]:
import sys
from pymongo import MongoClient
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import operator
import json
from bson.objectid import ObjectId
import pprint
import pandas as pd
import csv
import numpy as np
import re
import datefinder
from lightfm import LightFM
from sklearn.base import clone
from lightfm.data import Dataset
import random

In [2]:
stopwords = ["0o", "0s", "3a", "3b", "3d", "6b", "6o", "a", "a1", "a2", "a3", "a4", "ab", "able", "about", "above", "abst", "ac", "accordance", "according", "accordingly", "across", "act", "actually", "ad", "added", "adj", "ae", "af", "affected", "affecting", "affects", "after", "afterwards", "ag", "again", "against", "ah", "ain", "ain't", "aj", "al", "all", "allow", "allows", "almost", "alone", "along", "already", "also", "although", "always", "am", "among", "amongst", "amoungst", "amount", "an", "and", "announce", "another", "any", "anybody", "anyhow", "anymore", "anyone", "anything", "anyway", "anyways", "anywhere", "ao", "ap", "apart", "apparently", "appear", "appreciate", "appropriate", "approximately", "ar", "are", "aren", "arent", "aren't", "arise", "around", "as", "a's", "aside", "ask", "asking", "associated", "at", "au", "auth", "av", "available", "aw", "away", "awfully", "ax", "ay", "az", "b", "b1", "b2", "b3", "ba", "back", "bc", "bd", "be", "became", "because", "become", "becomes", "becoming", "been", "before", "beforehand", "begin", "beginning", "beginnings", "begins", "behind", "being", "believe", "below", "beside", "besides", "best", "better", "between", "beyond", "bi", "bill", "biol", "bj", "bk", "bl", "bn", "both", "bottom", "bp", "br", "brief", "briefly", "bs", "bt", "bu", "but", "bx", "by", "c", "c1", "c2", "c3", "ca", "call", "came", "can", "cannot", "cant", "can't", "cause", "causes", "cc", "cd", "ce", "certain", "certainly", "cf", "cg", "ch", "changes", "ci", "cit", "cj", "cl", "clearly", "cm", "c'mon", "cn", "co", "com", "come", "comes", "con", "concerning", "consequently", "consider", "considering", "contain", "containing", "contains", "corresponding", "could", "couldn", "couldnt", "couldn't", "course", "cp", "cq", "cr", "cry", "cs", "c's", "ct", "cu", "currently", "cv", "cx", "cy", "cz", "d", "d2", "da", "date", "dc", "dd", "de", "definitely", "describe", "described", "despite", "detail", "df", "di", "did", "didn", "didn't", "different", "dj", "dk", "dl", "do", "does", "doesn", "doesn't", "doing", "don", "done", "don't", "down", "downwards", "dp", "dr", "ds", "dt", "du", "due", "during", "dx", "dy", "e", "e2", "e3", "ea", "each", "ec", "ed", "edu", "ee", "ef", "effect", "eg", "ei", "eight", "eighty", "either", "ej", "el", "eleven", "else", "elsewhere", "em", "empty", "en", "end", "ending", "enough", "entirely", "eo", "ep", "eq", "er", "es", "especially", "est", "et", "et-al", "etc", "eu", "ev", "even", "ever", "every", "everybody", "everyone", "everything", "everywhere", "ex", "exactly", "example", "except", "ey", "f", "f2", "fa", "far", "fc", "few", "ff", "fi", "fifteen", "fifth", "fify", "fill", "find", "fire", "first", "firstname", "lastname", "username", "imgname", "admin", "groupsjoined","designation","bio", "rating","skills","skilldesc", "experience", "reviews","timestamps","posts", "false","five", "fix", "fj", "fl", "fn", "fo", "followed", "following", "follows", "for", "former", "formerly", "forth", "forty", "found", "four", "fr", "from", "front", "fs", "ft", "fu", "full", "further", "furthermore", "fy", "g", "ga", "gave", "ge", "get", "gets", "getting", "gi", "give", "given", "gives", "giving", "gj", "gl", "go", "goes", "going", "gone", "got", "gotten", "gr", "greetings", "gs", "gy", "h", "h2", "h3", "had", "hadn", "hadn't", "happens", "hardly", "has", "hasn", "hasnt", "hasn't", "have", "haven", "haven't", "having", "he", "hed", "he'd", "he'll", "hello", "help", "hence", "her", "here", "hereafter", "hereby", "herein", "heres", "here's", "hereupon", "hers", "herself", "hes", "he's", "hh", "hi", "hid", "him", "himself", "his", "hither", "hj", "ho", "home", "hopefully", "how", "howbeit", "however", "how's", "hr", "hs", "http", "hu", "hundred", "hy", "i", "i2", "i3", "i4", "i6", "i7", "i8", "ia", "ib", "ibid", "ic", "id", "i'd", "ie", "if", "ig", "ignored", "ih", "ii", "ij", "il", "i'll", "im", "i'm", "immediate", "immediately", "importance", "important", "in", "inasmuch", "inc", "indeed", "index", "indicate", "indicated", "indicates", "information", "inner", "insofar", "instead", "interest", "into", "invention", "inward", "io", "ip", "iq", "ir", "is", "isn", "isn't", "it", "itd", "it'd", "it'll", "its", "it's", "itself", "iv", "i've", "ix", "iy", "iz", "j", "jj", "jr", "js", "jt", "ju", "just", "k", "ke", "keep", "keeps", "kept", "kg", "kj", "km", "know", "known", "knows", "ko", "l", "l2", "la", "largely", "last", "lately", "later", "latter", "latterly", "lb", "lc", "le", "least", "les", "less", "lest", "let", "lets", "let's", "lf", "like", "liked", "likely", "line", "little", "lj", "ll", "ll", "ln", "lo", "look", "looking", "looks", "los", "lr", "ls", "lt", "ltd", "m", "m2", "ma", "made", "mainly", "make", "makes", "many", "may", "maybe", "me", "mean", "means", "meantime", "meanwhile", "merely", "mg", "might", "mightn", "mightn't", "mill", "million", "mine", "miss", "ml", "mn", "mo", "more", "moreover", "most", "mostly", "move", "mr", "mrs", "ms", "mt", "mu", "much", "mug", "must", "mustn", "mustn't", "my", "myself", "n", "n2", "na", "name", "namely", "nay", "nc", "nd", "ne", "near", "nearly", "necessarily", "necessary", "need", "needn", "needn't", "needs", "neither", "never", "nevertheless", "new", "next", "ng", "ni", "nine", "ninety", "nj", "nl", "nn", "no", "nobody", "non", "none", "nonetheless", "noone", "nor", "normally", "nos", "not", "noted", "nothing", "novel", "now", "nowhere", "nr", "ns", "nt", "ny", "o", "oa", "ob", "obtain", "obtained", "obviously", "oc", "od", "of", "off", "often", "og", "oh", "oi", "oj", "ok", "okay", "ol", "old", "om", "omitted", "on", "once", "one", "ones", "only", "onto", "oo", "op", "oq", "or", "ord", "os", "ot", "other", "others", "otherwise", "ou", "ought", "our", "ours", "ourselves", "out", "outside", "over", "overall", "ow", "owing", "own", "ox", "oz", "p", "p1", "p2", "p3", "page", "pagecount", "pages", "par", "part", "particular", "particularly", "pas", "past", "pc", "pd", "pe", "per", "perhaps", "pf", "ph", "pi", "pj", "pk", "pl", "placed", "please", "plus", "pm", "pn", "po", "poorly", "possible", "possibly", "potentially", "pp", "pq", "pr", "predominantly", "present", "presumably", "previously", "primarily", "probably", "promptly", "proud", "provides", "ps", "pt", "pu", "put", "py", "q" , "qj", "qu", "que", "quickly", "quite", "qv", "r", "r2", "ra", "ran", "rather", "rc", "rd", "re", "readily", "really", "reasonably", "recent", "recently", "ref", "refs", "regarding", "regardless", "regards", "related", "relatively", "research", "research-articl", "respectively", "resulted", "resulting", "results", "rf", "rh", "ri", "right", "rj", "rl", "rm", "rn", "ro", "rq", "rr", "rs", "rt", "ru", "run", "rv", "ry", "s", "s2", "sa", "said", "same", "saw", "say", "saying", "says", "sc", "sd", "se", "sec", "second", "secondly", "section", "see", "seeing", "seem", "seemed", "seeming", "seems", "seen", "self", "selves", "sensible", "sent", "serious", "seriously", "seven", "several", "sf", "shall", "shan", "shan't", "she", "shed", "she'd", "she'll", "shes", "she's", "should", "shouldn", "shouldn't", "should've", "show", "showed", "shown", "showns", "shows", "si", "side", "significant", "significantly", "similar", "similarly", "since", "sincere", "six", "sixty", "sj", "sl", "slightly", "sm", "sn", "so", "some", "somebody", "somehow", "someone", "somethan", "something", "sometime", "sometimes", "somewhat", "somewhere", "soon", "sorry", "sp", "specifically", "specified", "specify", "specifying", "sq", "sr", "ss", "st", "still", "stop", "strongly", "sub", "substantially", "successfully", "such", "sufficiently", "suggest", "sup", "sure", "sy", "system", "sz", "t", "t1", "t2", "t3", "take", "taken", "taking", "tb", "tc", "td", "te", "tell", "ten", "tends", "tf", "th", "than", "thank", "thanks", "thanx", "that", "that'll", "thats", "that's", "that've", "the", "their", "theirs", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "thered", "therefore", "therein", "there'll", "thereof", "therere", "theres", "there's", "thereto", "thereupon", "there've", "these", "they", "theyd", "they'd", "they'll", "theyre", "they're", "they've", "thickv", "thin", "think", "third", "this", "thorough", "thoroughly", "those", "thou", "though", "thoughh", "thousand", "three", "throug", "through", "throughout", "thru", "thus", "ti", "til", "tip", "tj", "tl", "tm", "tn", "to", "together", "too", "took", "top", "toward", "towards", "tp", "tq", "tr", "tried", "tries", "truly", "try", "trying", "ts", "t's", "tt", "tv", "twelve", "twenty", "twice", "two", "tx", "u", "u201d", "ue", "ui", "uj", "uk", "um", "un", "under", "unfortunately", "unless", "unlike", "unlikely", "until", "unto", "uo", "up", "upon", "ups", "ur", "us", "use", "used", "useful", "usefully", "usefulness", "uses", "using", "usually", "ut", "v", "va", "value", "various", "vd", "ve", "ve", "very", "via", "viz", "vj", "vo", "vol", "vols", "volumtype", "vq", "vs", "vt", "vu", "w", "wa", "want", "wants", "was", "wasn", "wasnt", "wasn't", "way", "we", "wed", "we'd", "welcome", "well", "we'll", "well-b", "went", "were", "we're", "weren", "werent", "weren't", "we've", "what", "whatever", "what'll", "whats", "what's", "when", "whence", "whenever", "when's", "where", "whereafter", "whereas", "whereby", "wherein", "wheres", "where's", "whereupon", "wherever", "whether", "which", "while", "whim", "whither", "who", "whod", "whoever", "whole", "who'll", "whom", "whomever", "whos", "who's", "whose", "why", "why's", "wi", "widely", "will", "willing", "wish", "with", "within", "without", "wo", "won", "wonder", "wont", "won't", "words", "world", "would", "wouldn", "wouldnt", "wouldn't", "www", "x", "x1", "x2", "x3", "xf", "xi", "xj", "xk", "xl", "xn", "xo", "xs", "xt", "xv", "xx", "y", "y2", "yes", "yet", "yj", "yl", "you", "youd", "you'd", "you'll", "your", "youre", "you're", "yours", "yourself", "yourselves", "you've", "yr", "ys", "yt", "z", "zero", "zi", "zz"]
stopwords=[i.replace('"',"").strip() for i in stopwords]

In [3]:
#user data
client = MongoClient(port = 27017)

mydb = client["conFusion"]
myusers= mydb['users']

userData = pd.DataFrame(list(myusers.find({})))
userData = userData.drop(['firstname','lastname','imgname','admin','rating','followersCount','followingCount','reviews','groupsjoined','createdAt','updatedAt','__v','project','githubusername','posts','followers','following','salt','hash'], axis=1)
userData

,_id,designation,bio,skills,skilldesc,experience,username
0,5fb199445a4b00472c11fd93,soft dev,mera man nhi likna ka,[{'skillname': 'nodejs'}],idntknw,[{'exp': 'something'}],ishan
1,5fb1994c5a4b00472c11fd94,,,[],false,[],nauki
2,5fb199545a4b00472c11fd95,,,[],false,[],nikhil
3,5fb1995b5a4b00472c11fd96,,,[],false,[],vishal
4,5fc724d14ed7bb24804607db,,,[],false,[],manisha
5,5fc7255d427b6820a0e57b7d,,,[],false,[],jaya
6,5fc725af42b23f09dc0c6228,,,[],false,[],jay
7,5fc7282ec64c424174bbd219,,,[],false,[],jayaa
8,5fc7288372683809a438d3b9,,,[],false,[],vishaal
9,5fc728c1d5695c43e0724949,,,[],false,[],vishaaal
10,5fc72908e4dc173cd4330f73,,,[],false,[],vishaaaal
11,5fc729319c27ba4b88e1cadd,,,[],false,[],vishaaaaal
12,5fc729dd6b10ea3bd821c2fe,,,[],false,[],vish
13,5fc72c435de48e4058dfbd16,,,[],false,[],vis
14,5fc72c625de48e4058dfbd17,,,[],false,[],vi
15,5fc72c965de48e4058dfbd18,,,[],false,[],viss
16,5fc72d615de48e4058dfbd19,,,[],false,[],vissa
17,5fc72e543058ef05e8c83c2a,,,[],false,[],vissas
18,5fc72f56f238e02c5862b087,,,[],false,[],visssaas
19,5fc730faf238e02c5862b088,,,[],false,[],vissssaas

In [4]:
userFeatures = []
for i in userData.index:
    words = [] + word_tokenize(userData['designation'][i].lower()) +  word_tokenize(userData['bio'][i].lower()) +  word_tokenize(userData['skilldesc'][i].lower())
    for skill in userData['skills'][i]:
        words += [skill['skillname']]
    for experience in userData['experience'][i]:
        words += [experience['exp']]
    words = [word for word in words if word.lower() not in stopwords]
    for word in words:
        word = re.sub('http[s]?://\S+', 'url', word)
        word = re.sub('\S+@\S+','email',word)
        word = re.sub(r'[0-9]+', ' number ', word)
        word = re.sub('[^A-Za-z]', ' ', word)
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words] 
    words = [word for word in words if len(word)>2]
    userFeatures.append(words)
userData['features'] =  userFeatures
userData['num_id'] = list(range(0,len(userData)))
userData.to_csv('userData.csv')
userData

,_id,designation,bio,skills,skilldesc,experience,username,features,num_id
0,5fb199445a4b00472c11fd93,soft dev,mera man nhi likna ka,[{'skillname': 'nodejs'}],idntknw,[{'exp': 'something'}],ishan,"[soft, dev, mera, man, nhi, likna, idntknw, no...",0
1,5fb1994c5a4b00472c11fd94,,,[],false,[],nauki,[],1
2,5fb199545a4b00472c11fd95,,,[],false,[],nikhil,[],2
3,5fb1995b5a4b00472c11fd96,,,[],false,[],vishal,[],3
4,5fc724d14ed7bb24804607db,,,[],false,[],manisha,[],4
5,5fc7255d427b6820a0e57b7d,,,[],false,[],jaya,[],5
6,5fc725af42b23f09dc0c6228,,,[],false,[],jay,[],6
7,5fc7282ec64c424174bbd219,,,[],false,[],jayaa,[],7
8,5fc7288372683809a438d3b9,,,[],false,[],vishaal,[],8
9,5fc728c1d5695c43e0724949,,,[],false,[],vishaaal,[],9
10,5fc72908e4dc173cd4330f73,,,[],false,[],vishaaaal,[],10
11,5fc729319c27ba4b88e1cadd,,,[],false,[],vishaaaaal,[],11
12,5fc729dd6b10ea3bd821c2fe,,,[],false,[],vish,[],12
13,5fc72c435de48e4058dfbd16,,,[],false,[],vis,[],13
14,5fc72c625de48e4058dfbd17,,,[],false,[],vi,[],14
15,5fc72c965de48e4058dfbd18,,,[],false,[],viss,[],15
16,5fc72d615de48e4058dfbd19,,,[],false,[],vissa,[],16
17,5fc72e543058ef05e8c83c2a,,,[],false,[],vissas,[],17
18,5fc72f56f238e02c5862b087,,,[],false,[],visssaas,[],18
19,5fc730faf238e02c5862b088,,,[],false,[],vissssaas,[],19

In [5]:
userMatrix = pd.DataFrame(list(myusers.find({})))
userMatrix = userMatrix[['_id', 'following']]
userMatrix['num_id'] =  list(range(0,len(userMatrix)))
xyz = pd.DataFrame(columns = ['_id','following','num_id','num_id_following'])
for i in userMatrix.index:
    for follow in userMatrix['following'][i]:
        xyz.loc[len(xyz)] = [userMatrix['_id'][i], follow, userMatrix['num_id'][i], int(userMatrix[userMatrix['_id'] == follow]['num_id'])]
userMatrix = xyz
userMatrix.to_csv('user_interactions.csv')
userMatrix

                        _id                 following num_id num_id_following
0  5fb199445a4b00472c11fd93  5fb1994c5a4b00472c11fd94      0                1
1  5fb199445a4b00472c11fd93  5fb199545a4b00472c11fd95      0                2
2  5fb199445a4b00472c11fd93  5fb1995b5a4b00472c11fd96      0                3
3  5fb1994c5a4b00472c11fd94  5fb1995b5a4b00472c11fd96      1                3
4  5fb199545a4b00472c11fd95  5fb1995b5a4b00472c11fd96      2                3

In [6]:
# group data
mygroups= mydb['groups']

groupData = pd.DataFrame(list(mygroups.find({})))
groupData = groupData.drop(['admin','users','file','createdAt','updatedAt','__v'], axis = 1)
groupData

                        _id           description      name
0  5fc74bd78b7b454220f96421  this is a test group    testga
1  5fc764ed8b7b454220f96424  this is a test group  testga 1

In [7]:
groupFeatures = []
for i in groupData.index:
    words = [] + word_tokenize(groupData['description'][i].lower()) +  word_tokenize(groupData['name'][i].lower())
    words = [word for word in words if word.lower() not in stopwords]
    for word in words:
        word = re.sub('http[s]?://\S+', 'url', word)
        word = re.sub('\S+@\S+','email',word)
        word = re.sub(r'[0-9]+', ' number ', word)
        word = re.sub('[^A-Za-z]', ' ', word)
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words] 
    words = [word for word in words if len(word)>2]
    groupFeatures.append(words)
groupData['features'] = groupFeatures
groupData['num_id'] = list(range(0,len(groupData)))
groupData.to_csv('groupData.csv')
groupData

,_id,description,name,features,num_id
0,5fc74bd78b7b454220f96421,this is a test group,testga,"[test, group, testga]",0
1,5fc764ed8b7b454220f96424,this is a test group,testga 1,"[test, group, testga]",1

In [8]:
groupMatrix = pd.DataFrame(list(myusers.find({})))
groupMatrix = groupMatrix[['_id',  'groupsjoined']]
groupMatrix['num_id'] =  list(range(0,len(groupMatrix)))
groupMatrix
xyz = pd.DataFrame(columns = ['_id','groupsjoined','num_id','num_id_groups'])
for i in groupMatrix.index:
    for group in groupMatrix['groupsjoined'][i]:
        xyz.loc[len(xyz)] = [groupMatrix['_id'][i], group['id'], groupMatrix['num_id'][i], int(groupData[groupData['_id'] == ObjectId(group['id'])]['num_id'])]
groupMatrix = xyz
groupMatrix.to_csv('group_interactions.csv')
groupMatrix

                        _id              groupsjoined num_id num_id_groups
0  5fb199445a4b00472c11fd93  5fc74bd78b7b454220f96421      0             0
1  5fb199445a4b00472c11fd93  5fc764ed8b7b454220f96424      0             1

In [9]:
# post data

myposts= mydb['posts']

postData = pd.DataFrame(list(myposts.find({})))
postData = postData.drop(['author','upvote','upvotecount','upvotebool','group','comments','commentcount','file','createdAt','updatedAt','__v'], axis = 1)
postData

                        _id               message   title
0  5fc74d848b7b454220f96423  this is a test group  testga

In [10]:
postFeatures = []
for i in postData.index:
    words = [] + word_tokenize(postData['message'][i].lower()) + word_tokenize(postData['title'][i].lower())
    words = [word for word in words if word.lower() not in stopwords]
    for word in words:
        word = re.sub('http[s]?://\S+', 'url', word)
        word = re.sub('\S+@\S+','email',word)
        word = re.sub(r'[0-9]+', ' number ', word)
        word = re.sub('[^A-Za-z]', ' ', word)
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words] 
    words = [word for word in words if len(word)>2]
    postFeatures.append(words)
postData['features'] = postFeatures
postData['num_id'] = list(range(0,len(postData)))
postData.to_csv('postData.csv')
postData

,_id,message,title,features,num_id
0,5fc74d848b7b454220f96423,this is a test group,testga,"[test, group, testga]",0

In [13]:
class LightFMResizable(LightFM):
    """A LightFM that resizes the model to accomodate new users,
    items, and features"""

    def fit_partial(
        self,
        interactions,
        user_features=None,
        item_features=None,
        sample_weight=None,
        epochs=1,
        num_threads=1,
        verbose=False,
    ):
        try:
            self._check_initialized()
            self._resize(interactions, user_features, item_features)
        except ValueError:
            # This is the first call so just fit without resizing
            pass

        super().fit_partial(
            interactions,
            user_features,
            item_features,
            sample_weight,
            epochs,
            num_threads,
            verbose,
        )

        return self

    def _resize(self, interactions, user_features=None, item_features=None):
        """Resizes the model to accommodate new users/items/features"""

        no_components = self.no_components
        no_user_features, no_item_features = interactions.shape  # default

        if hasattr(user_features, "shape"):
            no_user_features = user_features.shape[-1]
        if hasattr(item_features, "shape"):
            no_item_features = item_features.shape[-1]

        if (
            no_user_features == self.user_embeddings.shape[0]
            and no_item_features == self.item_embeddings.shape[0]
        ):
            return self

        new_model = clone(self)
        new_model._initialize(no_components, no_item_features, no_user_features)

        # update all attributes from self._check_initialized
        for attr in (
            "item_embeddings",
            "item_embedding_gradients",
            "item_embedding_momentum",
            "item_biases",
            "item_bias_gradients",
            "item_bias_momentum",
            "user_embeddings",
            "user_embedding_gradients",
            "user_embedding_momentum",
            "user_biases",
            "user_bias_gradients",
            "user_bias_momentum",
        ):
            # extend attribute matrices with new rows/cols from
            # freshly initialized model with right shape
            old_array = getattr(self, attr)
            old_slice = [slice(None, i) for i in old_array.shape]
            new_array = getattr(new_model, attr)
            new_array[tuple(old_slice)] = old_array
            setattr(self, attr, new_array)

        return self

In [24]:
# user recommendations
user_features = []
for i in userData.index:
    user_features += userData['features'][i]
user_features = np.array(user_features)
user_features =list(np.unique(user_features))
group_features = []
for i in groupData.index:
    group_features += groupData['features'][i]
group_features = np.array(group_features)
group_features =list(np.unique(group_features))

In [29]:
user_features_list = list(zip(userData[['num_id']],userData[['features']]))

In [42]:
userRecommendation = userData
userlist = list(userRecommendation['_id'])
user_rec_list = []
for i in userData.index:
    random.shuffle(userlist)
    user_rec_list.append(userlist)
userRecommendation['recommendations'] = user_rec_list